; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv32 -mattr=+m -verify-machineinstrs < %s | FileCheck %s --check-prefix=GENERIC
; RUN: llc -mtriple=riscv32 -mcpu=hb-rv32 -mattr=+m -verify-machineinstrs < %s | FileCheck %s --check-prefix=HB

; Vanilla implements low-word MUL but traps the three high-word M-extension
; instructions. The HB processor model must expand this operation without
; weakening normal RV32M lowering.

define i32 @umul_high(i32 %a, i32 %b) {
; GENERIC-LABEL: umul_high:
; GENERIC:       # %bb.0:
; GENERIC-NEXT:    mulhu a0, a0, a1
; GENERIC-NEXT:    ret
;
; HB-LABEL: umul_high:
; HB:       # %bb.0:
; HB-NOT:     mulh
; HB:         ret
  %a64 = zext i32 %a to i64
  %b64 = zext i32 %b to i64
  %product = mul i64 %a64, %b64
  %high64 = lshr i64 %product, 32
  %high = trunc i64 %high64 to i32
  ret i32 %high
}
